quarkus.application.name=politicas-service
quarkus.http.port=8080

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=neondb_owner
quarkus.datasource.password=npg_Qnpf3C1KBYOV
quarkus.datasource.jdbc.url=jdbc:postgresql://ep-muddy-shadow-aezoaki0-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
quarkus.datasource.devservices.enabled=false

quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.jdbc.timezone=UTC

# ---- Perfil test ----
%quarkus.datasource.db-kind=postgresql
%quarkus.datasource.username=neondb_owner
%quarkus.datasource.password=npg_Qnpf3C1KBYOV
%quarkus.datasource.jdbc.url=jdbc:postgresql://ep-muddy-shadow-aezoaki0-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
%test.quarkus.datasource.devservices.enabled=false
%test.quarkus.hibernate-orm.database.generation=drop-and-create
%test.quarkus.hibernate-orm.log.sql=false