quarkus.application.name=ms-reportes
quarkus.http.port=8086

quarkus.mongodb.connection-string=mongodb://${MONGO_INITDB_ROOT_USERNAME:mongo_user}:${MONGO_INITDB_ROOT_PASSWORD:mongo_pass}@${MONGO_HOST:localhost}:27017/?authSource=admin
# Misma base de lectura que ms-consultas: CQRS con un unico modelo de lectura en Mongo.
quarkus.mongodb.database=${MONGO_DB:consultas_db}

quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.info-title=ms-reportes API
quarkus.smallrye-openapi.info-version=1.0.0
