#quarkus.datasource.db-kind = h2
#quarkus.datasource.jdbc.url = jdbc:h2:./db
#quarkus.hibernate-orm.database.generation = update

# ==========================================
# CONFIGURACIÓN PARA POSTGRESQL
# ==========================================

# 1. Indicar el tipo de base de datos
quarkus.datasource.db-kind=postgresql

quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:4200
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS,HEAD
quarkus.http.cors.headers=accept,authorization,content-type

# 2. Estrategia de Hibernate (Generación de tablas)
# 'update' actualiza el esquema, 'drop-and-create' es buena para pruebas limpias
quarkus.hibernate-orm.generation=update

# Opcional: Para ver las consultas SQL que se ejecutan en la consola
quarkus.hibernate-orm.log.sql=true

# Configuración Global de Kafka
#kafka.bootstrap.servers=localhost:notengonadamontadoaunparakafka

# --- CANAL DE SALIDA: Publicar 'solicitud-creada' (Hacia el Broker) ---
mp.messaging.outgoing.solicitud-creada.connector=smallrye-kafka
mp.messaging.outgoing.solicitud-creada.topic=solicitud-creada
mp.messaging.outgoing.solicitud-creada.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
