quarkus.application.name=ms-consultas
quarkus.http.port=8084

# CORS deshabilitado: se gestiona en el api-gateway

# MongoDB (Read Model CQRS)
quarkus.mongodb.connection-string=mongodb://${MONGO_INITDB_ROOT_USERNAME:mongo_user}:${MONGO_INITDB_ROOT_PASSWORD:mongo_pass}@${MONGO_HOST:localhost}:27017/?authSource=admin
quarkus.mongodb.database=${MONGO_DB:consultas_db}

# Kafka
kafka.bootstrap.servers=${KAFKA_BOOTSTRAP:localhost:9092}

# Consumidor: solicitud.creada
mp.messaging.incoming.solicitud-creada-in.connector=smallrye-kafka
mp.messaging.incoming.solicitud-creada-in.topic=solicitud.creada
mp.messaging.incoming.solicitud-creada-in.group.id=ms-consultas-group
mp.messaging.incoming.solicitud-creada-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.solicitud-creada-in.auto.offset.reset=earliest

# Consumidor: solicitud.aprobada
mp.messaging.incoming.solicitud-aprobada-in.connector=smallrye-kafka
mp.messaging.incoming.solicitud-aprobada-in.topic=solicitud.aprobada
mp.messaging.incoming.solicitud-aprobada-in.group.id=ms-consultas-group
mp.messaging.incoming.solicitud-aprobada-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.solicitud-aprobada-in.auto.offset.reset=earliest

# Consumidor: solicitud.rechazada
mp.messaging.incoming.solicitud-rechazada-in.connector=smallrye-kafka
mp.messaging.incoming.solicitud-rechazada-in.topic=solicitud.rechazada
mp.messaging.incoming.solicitud-rechazada-in.group.id=ms-consultas-group
mp.messaging.incoming.solicitud-rechazada-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.solicitud-rechazada-in.auto.offset.reset=earliest

# Consumidor: solicitud.cancelada
mp.messaging.incoming.solicitud-cancelada-in.connector=smallrye-kafka
mp.messaging.incoming.solicitud-cancelada-in.topic=solicitud.cancelada
mp.messaging.incoming.solicitud-cancelada-in.group.id=ms-consultas-group
mp.messaging.incoming.solicitud-cancelada-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.solicitud-cancelada-in.auto.offset.reset=earliest

quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.info-title=ms-consultas API
quarkus.smallrye-openapi.info-version=1.0.0
