FROM maven:3.9.8-eclipse-temurin-17 AS build
WORKDIR /workspace

COPY . .
RUN mvn -pl ms-notificaciones -am -DskipTests -Dquarkus.package.jar.type=uber-jar package

FROM eclipse-temurin:17-jre-alpine
WORKDIR /deployments

COPY --from=build /workspace/ms-notificaciones/target/*-runner.jar /deployments/app.jar

EXPOSE 8084
ENTRYPOINT ["java", "-Dquarkus.http.host=0.0.0.0", "-jar", "/deployments/app.jar"]
