@baseUrl = http://localhost:8080
@politicaId = 1

### Crear politica
POST {{baseUrl}}/politicas
Content-Type: application/json

{
  "nombre": "Politica temporal QA",
  "tipoVacacion": "ANUAL",
  "diasBaseAnio": 15,
  "antiguedadMinimaMeses": 12,
  "acumulable": true,
  "maxDiasAcumulables": 30,
  "activa": true
}

### Consultar politica por id
GET {{baseUrl}}/politicas/{{politicaId}}

### Actualizar politica
PUT {{baseUrl}}/politicas/{{politicaId}}
Content-Type: application/json

{
  "nombre": "Politica temporal QA actualizada",
  "tipoVacacion": "ANUAL",
  "diasBaseAnio": 20,
  "antiguedadMinimaMeses": 12,
  "acumulable": true,
  "maxDiasAcumulables": 35,
  "activa": true
}

### Listar todas las politicas
GET {{baseUrl}}/politicas

### Eliminar politica
DELETE {{baseUrl}}/politicas/{{politicaId}}