####
# Imagen nativa. Build:
#   ./mvnw package -Dnative -Dquarkus.native.container-build=true
#   docker build -f src/main/docker/Dockerfile.native -t mcsv-gateway-native .
# Run:
#   docker run -i --rm -p 8080:8080 mcsv-gateway-native
####
FROM registry.access.redhat.com/ubi9/ubi-minimal:9.6
WORKDIR /work/
RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work
COPY --chown=1001:root target/*-runner /work/application

EXPOSE 8080
USER 1001

ENTRYPOINT ["./application", "-Dquarkus.http.host=0.0.0.0"]
