####
# Imagen JVM (target/quarkus-app). Build:
#   ./mvnw package
#   docker build -f src/main/docker/Dockerfile.jvm -t mcsv-gateway-jvm .
# Run:
#   docker run -i --rm -p 8080:8080 mcsv-gateway-jvm
####
# FROM registry.access.redhat.com/ubi9/openjdk-25:1.24
FROM registry.access.redhat.com/ubi9/openjdk-25-runtime:1.24

ENV LANGUAGE='en_US:en'

COPY --chown=185 target/quarkus-app/lib/ /deployments/lib/
COPY --chown=185 target/quarkus-app/*.jar /deployments/
COPY --chown=185 target/quarkus-app/app/ /deployments/app/
COPY --chown=185 target/quarkus-app/quarkus/ /deployments/quarkus/
# COPY --chown=185 target/classes/routes.json /deployments/config/routes.json
# COPY --chown=185 target/classes/publicKey.pem /deployments/config/publicKey.pem

EXPOSE 8081
USER 185

# ENV JAVA_OPTS_APPEND="-Dquarkus.http.host=0.0.0.0"
ENV JAVA_OPTS_APPEND="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
ENV JAVA_APP_JAR="/deployments/quarkus-run.jar"

ENTRYPOINT [ "/opt/jboss/container/java/run/run-java.sh" ]
